"""serial number added

Revision ID: 0f08efccb909
Revises: 54322f956efc
Create Date: 2026-02-28 09:20:12.666754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f08efccb909'
down_revision: Union[str, Sequence[str], None] = '54322f956efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herocard', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_herocard_serial_number'), 'herocard', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_herocard_serial_number'), table_name='herocard')
    op.drop_column('herocard', 'serial_number')
    # ### end Alembic commands ###
