"""hero card model added

Revision ID: 54322f956efc
Revises: 534dec11aea6
Create Date: 2026-02-26 10:42:55.572300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54322f956efc'
down_revision: Union[str, Sequence[str], None] = '534dec11aea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herocard',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('image_src', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('image_alt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_on_right', sa.Boolean(), nullable=False),
    sa.Column('cta_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bg_class', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herocard_id'), 'herocard', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_herocard_id'), table_name='herocard')
    op.drop_table('herocard')
    # ### end Alembic commands ###
